In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("../../SMAP_Climate_In_Situ.csv")
data = data.iloc[:946080,]

/Users/kehuiyao/Desktop/soil moisture/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3156: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
data.head(5)

Type POINTID            x             y      Date  prcp        srad  \
0  SMAP_grid       1 -9548038.561  3.710801e+06  20160101   0.0  147.199997   
1  SMAP_grid       1 -9548038.561  3.710801e+06  20160102   2.0  115.199997   
2  SMAP_grid       1 -9548038.561  3.710801e+06  20160103   7.0  137.600006   
3  SMAP_grid       1 -9548038.561  3.710801e+06  20160104   0.0  310.399994   
4  SMAP_grid       1 -9548038.561  3.710801e+06  20160105   0.0  300.799988   

   tmax  tmin     vp  ...  In_situ  elevation  slope  aspect  hillshade  clay  \
0   7.5   1.5  680.0  ...      NaN      547.0    1.0   327.0      182.0  27.0   
1   7.0   2.5  720.0  ...      NaN      547.0    1.0   327.0      182.0  27.0   
2   9.0   1.5  680.0  ...      NaN      547.0    1.0   327.0      182.0  27.0   
3  12.5  -2.5  520.0  ...      NaN      547.0    1.0   327.0      182.0  27.0   
4  12.5  -1.5  560.0  ...      NaN      547.0    1.0   327.0      182.0  27.0   

   sand     bd  soc    LC  
0  37.0  151.0  5.0  52.0  
1  37.0  151.0  5.0  52.0  
2  37.0  151.0  5.0  52.0  
3  37.0  151.0  5.0  52.0  
4  37.0  151.0  5.0  52.0  

[5 rows x 22 columns]

In [4]:
len(data.POINTID.unique())

1297

In [5]:
len(data.Date.unique())

730

In [6]:
data.dtypes

Type          object
POINTID       object
x            float64
y            float64
Date           int64
prcp         float64
srad         float64
tmax         float64
tmin         float64
vp           float64
SMAP_36km    float64
SMAP_1km     float64
In_situ      float64
elevation    float64
slope        float64
aspect       float64
hillshade    float64
clay         float64
sand         float64
bd           float64
soc          float64
LC           float64
dtype: object

In [7]:
data['formatted_date'] = pd.to_datetime(data.Date, format='%Y%m%d')

In [8]:
data['mask'] = 1
data['mask'][pd.isna(data.SMAP_36km)] = 0
data['mask']

/Users/kehuiyao/Desktop/soil moisture/venv/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


0         0
1         1
2         0
3         1
4         1
         ..
946075    1
946076    0
946077    0
946078    1
946079    0
Name: mask, Length: 946080, dtype: int64

In [9]:
data['month'] = data['formatted_date'].dt.month

In [10]:
data['month']

0          1
1          1
2          1
3          1
4          1
          ..
946075    12
946076    12
946077    12
946078    12
946079    12
Name: month, Length: 946080, dtype: int64

In [11]:
data.iloc[946079:946080,:]

Type POINTID            x             y      Date  prcp  \
946079  SMAP_grid     999 -9522038.561  3.683801e+06  20171231   0.0   

              srad  tmax  tmin     vp  ...  aspect  hillshade  clay  sand  \
946079  281.600006  11.5   0.0  600.0  ...    23.0      180.0  27.0  38.0   

           bd  soc    LC  formatted_date  mask  month  
946079  160.0  4.0  52.0      2017-12-31     0     12  

[1 rows x 25 columns]

In [12]:
data['SMAP_36km'][pd.isna(data['SMAP_36km'])] = 0
data['SMAP_36km']
    

/Users/kehuiyao/Desktop/soil moisture/venv/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


0         0.000000
1         0.234458
2         0.000000
3         0.255353
4         0.249691
            ...   
946075    0.187667
946076    0.000000
946077    0.000000
946078    0.196625
946079    0.000000
Name: SMAP_36km, Length: 946080, dtype: float64

In [13]:
N = len(data[~data.duplicated(subset = ['POINTID','month'])])
N

15556

In [14]:
data['index'] = list(range(data.shape[0]))
ind_list = data['index'][~data.duplicated(subset = ['POINTID','month'])]
ind_list = list(ind_list) + [data.shape[0]]

In [15]:
ind_list[-3:-1]

[945654, 945684]

In [16]:
data[['x','y']]

x             y
0      -9548038.561  3.710801e+06
1      -9548038.561  3.710801e+06
2      -9548038.561  3.710801e+06
3      -9548038.561  3.710801e+06
4      -9548038.561  3.710801e+06
...             ...           ...
946075 -9522038.561  3.683801e+06
946076 -9522038.561  3.683801e+06
946077 -9522038.561  3.683801e+06
946078 -9522038.561  3.683801e+06
946079 -9522038.561  3.683801e+06

[946080 rows x 2 columns]

In [17]:
data.elevation.unique()

array([547., 535., 431., 450., 451., 455., 449., 448., 453., 439., 516.,
       400., 511., 504., 503., 499., 497., 495., 493., 492., 489., 486.,
       373., 485., 480., 483., 491., 481., 476., 469., 368., 464., 462.,
       460., 457., 459., 461., 374., 471., 441., 512., 508., 513., 395.,
       506., 505., 501., 396., 534., 519., 510., 478., 479., 466., 465.,
       383., 468., 463., 477., 470., 482., 397., 530., 532., 527., 528.,
       600., 498., 507., 525., 533., 548., 612., 475., 488., 473., 632.,
       494., 515., 538., 635., 544., 555., 554., 561., 552., 629., 560.,
       549., 524., 472., 627., 496., 490., 509., 621., 458., 539., 526.,
       576., 591., 587., 582., 543., 562., 574., 571., 541., 611., 500.,
       484., 520., 583., 559., 542., 596., 594., 579., 536., 545., 565.,
       577., 589., 586., 573., 550., 537., 531., 588., 568., 595., 581.,
       518., 564., 593., 572., 578., 569., 557., 551., 521., 522., 546.,
       523., 540., 403., 404., 411., 402., 417., 63

In [18]:
data.slope.unique()

array([1., 2., 0., 3., 5., 4.])

In [19]:
data.aspect.unique()

array([327.,   9.,  99.,   0., 333.,  29.,  23.,   3., 341., 351.,  69.,
       135., 102., 113.,  54.,  49.,  45.,  60., 100.,  18.,  43.,  51.,
       342., 354.,  11.,  19.,  14., 356.,  27., 334.,  34.,   4., 345.,
       344., 305., 358., 347., 355.,  55.,   6.,  17.,  16., 319.,  25.,
        44., 331.,  22., 348.,  33.,  53.,  39.,  47.,  36., 340., 313.,
       339.,  89., 328., 324.,  63., 317.,  15., 353.,   2.,  77.,  13.,
       337., 343., 350., 150., 127., 114., 346.,  98.,  82., 105.,  12.,
        21., 280., 291.,  81., 117., 106.,  78., 326., 263., 116.,   1.,
        48., 332., 163.,  92., 122., 137., 109., 336., 164.,   5.,  32.,
       296., 110., 154., 119., 293., 255.,  64.,  80., 325., 338.,  24.,
        88.,  94.,  97., 349., 294., 335.,   7.,  95.,  67.,  38.,  70.,
       271., 264.,  84., 111.,  83.,  76., 329.,  87., 132., 152.,  90.,
        28., 244., 275., 357.,  31., 298., 153., 303., 225., 193., 301.,
       318., 118., 147., 138., 180., 126.,  46., 25

In [20]:
data.hillshade.unique()

array([182., 179., 174., 180., 181., 175., 183., 178., 177., 176., 184.,
       185., 173., 172., 187., 186., 167., 170.])

In [21]:
data.clay.unique()


array([27., 26., 28., 30., 29., 25., 23., 22., 31., 24., 32.])

In [22]:
data.sand.unique()

array([37., 42., 51., 39., 40., 36., 38., 35., 53., 41., 46., 45., 43.,
       44., 47., 49., 48., 50., 52., 55.])

In [23]:
data.bd.unique()


array([151., 149., 148., 158., 157., 160., 159., 154., 147., 153., 155.,
       156., 150., 161., 152., 142., 144., 143., 145., 140., 141., 146.])

In [24]:
data.soc.unique()

array([5., 4., 3., 2., 6.])

In [25]:
data.LC.unique()

array([52., 21., 71., 81., 82., 42., 24.])